### ISSUE TITLE
Add support for global .lldbinit via ~/.lldbinit?

### ISSUE THREAD

**Issue by orta** [alloy/LLDB-Is-It-Not#1]
I use lldb via Xcode's user breakpoints

![screen shot 2015-11-27 at 4 38 14 pm](https://cloud.githubusercontent.com/assets/49038/11448398/48b20fb8-9525-11e5-8f7f-909d2340b7f9.png)

If I could get that systematized, then I can also use it on other [projects](https://github.com/orta/PonyDebuggerApp)

**Comment by alloy** [comment]
Not sure I completely follow, `~/.lldbinit` already works, so I’m guessing you’re asking how to setup the breakpoint and attach the action?

**Comment by orta** [comment]
oh, I didn't know this! No worries.
